image: dxjoke/docker-angular-ci-build
stages:
  - build
  - test
  - deploy

before_script:
  - npm install

app-build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm run build -- --prod --base-href "https://sebhn.github.io/mvs/"

unit-tests:
  stage: test
  script:
    - npm test

deployment:
  stage: deploy
  script:
    - npx ngh --dir=dist/spring-frontend --repo=https://$GH_TOKEN@github.com/SEBHN/mvs.git --name="MVS Publisher" --email=443_3w4md4sjdioa@byom.de