image: dxjoke/docker-angular-ci-build
stages:
  - build
  - test
  - deploy


app-build:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build

app-build-production:
  stage: build
  artifacts:
    paths:
      - dist/
    expire_in: 10 mins
  before_script:
    - npm install
  script:
    - ng build --prod --base-href "https://sebhn.github.io/mvs/" 

unit-tests:
  stage: test
  before_script:
    - npm install
  script:
    - npm test

deployment:
  stage: deploy
  dependencies:
    - app-build-production
  script:
    - npx ngh --dir=dist/spring-frontend --repo=https://$GH_TOKEN@github.com/SEBHN/mvs.git --name="MVS Publisher" --email=443_3w4md4sjdioa@byom.de
  only:
    - develop
    - master
    - build