image: juristr/angular-ci-build:1.0.0
stages:
  - build
  - test
  - deploy
  
before_script:
  - npm install
  
app-build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm run build

unit-tests:
  stage: test
  script:
    - npm test